"""初始化数据库结构"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


revision: str = '7849a7154002'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=True),
    sa.Column('grade', sa.String(length=128), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_status'), 'lessons', ['status'], unique=False)
    op.create_index(op.f('ix_lessons_teacher_id'), 'lessons', ['teacher_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=127), nullable=False),
    sa.Column('extension', sa.String(length=16), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_extension'), 'materials', ['extension'], unique=False)
    op.create_index(op.f('ix_materials_status'), 'materials', ['status'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_ref', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('media_ref', sa.String(length=1024), nullable=True),
    sa.Column('modality', sa.String(length=32), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_material_id'), 'chunks', ['material_id'], unique=False)
    if op.get_bind().dialect.name == "postgresql":
        op.execute(sa.text(
            "CREATE INDEX IF NOT EXISTS ix_chunks_embedding_hnsw "
            "ON chunks USING hnsw (embedding vector_cosine_ops)"
        ))
    op.create_table('generation_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_jobs_lesson_id'), 'generation_jobs', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_status'), 'generation_jobs', ['status'], unique=False)
    op.create_table('gps_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gps_sessions_lesson_id'), 'gps_sessions', ['lesson_id'], unique=False)
    op.create_table('lesson_irs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('slots', sa.JSON(), nullable=False),
    sa.Column('dag_snapshot', sa.JSON(), nullable=False),
    sa.Column('reference_materials', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_irs_lesson_id'), 'lesson_irs', ['lesson_id'], unique=False)
    op.create_table('generated_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_artifacts_job_id'), 'generated_artifacts', ['job_id'], unique=False)
    op.create_index(op.f('ix_generated_artifacts_lesson_id'), 'generated_artifacts', ['lesson_id'], unique=False)
    op.create_table('rag_evidences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lesson_ir_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('page_ref', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('usage', sa.String(length=64), nullable=False),
    sa.Column('slot_binding', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['lesson_ir_id'], ['lesson_irs.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_evidences_lesson_ir_id'), 'rag_evidences', ['lesson_ir_id'], unique=False)
    op.create_index(op.f('ix_rag_evidences_material_id'), 'rag_evidences', ['material_id'], unique=False)
    op.create_table('edit_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('target_page', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('action_json', sa.JSON(), nullable=True),
    sa.Column('from_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_artifact_id'], ['generated_artifacts.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edit_requests_lesson_id'), 'edit_requests', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_edit_requests_status'), 'edit_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edit_requests_status'), table_name='edit_requests')
    op.drop_index(op.f('ix_edit_requests_lesson_id'), table_name='edit_requests')
    op.drop_table('edit_requests')
    op.drop_index(op.f('ix_rag_evidences_material_id'), table_name='rag_evidences')
    op.drop_index(op.f('ix_rag_evidences_lesson_ir_id'), table_name='rag_evidences')
    op.drop_table('rag_evidences')
    op.drop_index(op.f('ix_generated_artifacts_lesson_id'), table_name='generated_artifacts')
    op.drop_index(op.f('ix_generated_artifacts_job_id'), table_name='generated_artifacts')
    op.drop_table('generated_artifacts')
    op.drop_index(op.f('ix_lesson_irs_lesson_id'), table_name='lesson_irs')
    op.drop_table('lesson_irs')
    op.drop_index(op.f('ix_gps_sessions_lesson_id'), table_name='gps_sessions')
    op.drop_table('gps_sessions')
    op.drop_index(op.f('ix_generation_jobs_status'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_lesson_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_chunks_material_id'), table_name='chunks')
    if op.get_bind().dialect.name == "postgresql":
        op.execute(sa.text("DROP INDEX IF EXISTS ix_chunks_embedding_hnsw"))
    op.drop_table('chunks')
    op.drop_index(op.f('ix_materials_status'), table_name='materials')
    op.drop_index(op.f('ix_materials_extension'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_lessons_teacher_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_status'), table_name='lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###
